@startuml

title __MODEL's Class Diagram__\n

  namespace edu.ncsu.csc216.wolf_tasks.model {
    class edu.ncsu.csc216.wolf_tasks.model.Notebook {
        - notebookName : String
        - taskLists : List<TaskList>
        + Notebook()
        + addTaskList()
        + editTaskList()
        + getNotebookName()
        + getTaskLists()
        + removeTaskList()
        + setNotebookName()
        + setTaskLists()
        - rearrangeTaskList()
    }
  }
  

  namespace edu.ncsu.csc216.wolf_tasks.model {
    class edu.ncsu.csc216.wolf_tasks.model.Task {
        - description : String
        - isActive : boolean
        - isCompleted : boolean
        - isRecurring : boolean
        - priorityNumber : int
        - taskName : String
        + Task()
        + getDescription()
        + getPriorityNumber()
        + getTaskName()
        + isActive()
        + isCompleted()
        + isRecurring()
        + setActive()
        + setCompleted()
        + setDescription()
        + setPriorityNumber()
        + setRecurring()
        + setTaskName()
        + toString()
    }
  }
  

  namespace edu.ncsu.csc216.wolf_tasks.model {
    class edu.ncsu.csc216.wolf_tasks.model.TaskList {
        - completedTasksCount : int
        - taskListName : String
        - tasks : List<Task>
        + TaskList()
        + addTask()
        + deleteTask()
        + editTask()
        + getCompletedTasksCount()
        + getCurrentTask()
        + getSortedTaskList()
        + getTaskListName()
        + getTasks()
        + markTaskAsComplete()
        + moveTaskDown()
        + moveTaskToBack()
        + moveTaskToFront()
        + moveTaskUp()
        + setCompletedTasksCount()
        + setCurrentTask()
        + setTaskListName()
        + setTasks()
        + toString()
    }
  }
  

  edu.ncsu.csc216.wolf_tasks.model.TaskList o-- edu.ncsu.csc216.wolf_tasks.model.Task : currentTask


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
